### ISSUE TITLE
BSOD maybe related to gammalauncher

### ISSUE THREAD

**Issue by sunep** [sebescudie/GammaLauncher#62]
I tried launching gammalauncher, like normal, but then I got a BSOD.
Now after double restarts, I get the following error messange
![image](https://github.com/sebescudie/GammaLauncher/assets/5446771/e4d7e51d-983d-40ff-9a16-be9f67c54e69)
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(Stream stream, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(Stream stream)
   at VL.Lib.IO.XDocumentReader.Read(IResourceProvider`1 provider)
   at VL.Lib.IO.XDocumentReader.Update(IResourceProvider`1 input, Boolean read)
   at _VL_Xml_.System.XML.XMLReader_XDocument_OPrbd3hV1yTQAohaXbZTAZ.Update(Path File_Path_In, Boolean Read_In, XDocument& Output_Out)
   at _VL_Xml_.System.XML.XMLReader_OcM6yTDIunKLXht5WzCyyW.Update(Path File_Path_In, Boolean Read_In, XElement& Output_Out)
   at _GammaLauncher_.Main.Editor.File.UserSettingsInitializer_LzkfZhpne9PPdBDTgZZnhU.__Create__(NodeContext Node_Context, Channel`1 Input_In, Channel`1& Output_Out, Rectangle& Initial_Window_Bounds_Out)
   at _GammaLauncher_.Main.Editor.File.UserSettingsInitializer_LzkfZhpne9PPdBDTgZZnhU.Create(NodeContext Node_Context, Channel`1 Input_In, Channel`1& Output_Out, Rectangle& Initial_Window_Bounds_Out)
   at _GammaLauncher_.Main.App.App_C.__Create__(NodeContext Node_Context, String Version_In, Rectangle& Initial_Window_Bounds_Out)
   at _GammaLauncher_.Main.App.App_C.Create(NodeContext Node_Context, String Version_In, Rectangle& Initial_Window_Bounds_Out)
   at _GammaLauncher_.__auto.GammaLauncherApplication_OvsYGMYpBALLYRzDG73d7z.__Create__(NodeContext Node_Context)
   at _GammaLauncher_.__auto.GammaLauncherApplication_OvsYGMYpBALLYRzDG73d7z.Create(NodeContext Node_Context)
   at Program.<>c.<Main>b__0_0(NodeContext c)
   at VL.AppServices.AppHost`1.<>c__DisplayClass10_1.<RunCoreAsync>b__1(Object _)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Private.CoreLib.dll
----------------------------------------
GammaLauncher
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/GammaLauncher/GammaLauncher.dll
----------------------------------------
System.Runtime
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Runtime.dll
----------------------------------------
Stride.Core
    Assembly Version: 4.1.0.1
    Win32 Version: 4.1.0.1
    CodeBase: file:///C:/Program%20Files/GammaLauncher/Stride.Core.dll
----------------------------------------
System.Collections
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Collections.dll
----------------------------------------
System.Threading
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Threading.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Private.Uri.dll
----------------------------------------
ServiceWire
    Assembly Version: 5.3.4.0
    Win32 Version: 5.3.4.0
    CodeBase: file:///C:/Program%20Files/GammaLauncher/ServiceWire.dll
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/netstandard.dll
----------------------------------------
VL.Core
    Assembly Version: 2022.5.0.0
    Win32 Version: 2022.5.0
    CodeBase: file:///C:/Program%20Files/GammaLauncher/VL.Core.dll
----------------------------------------
Stride.Core.Mathematics
    Assembly Version: 4.1.0.1
    Win32 Version: 4.1.0.1
    CodeBase: file:///C:/Program%20Files/GammaLauncher/Stride.Core.Mathematics.dll
----------------------------------------
System.Linq
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Linq.dll
----------------------------------------
GammaLauncher.Proxies.vl
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/GammaLauncher/GammaLauncher.Proxies.vl.dll
----------------------------------------
VL.App.WindowsForms
    Assembly Version: 2022.5.0.0
    Win32 Version: 2022.5.0
    CodeBase: file:///C:/Program%20Files/GammaLauncher/VL.App.WindowsForms.dll
----------------------------------------
VL.AppServices
    Assembly Version: 2022.5.0.0
    Win32 Version: 2022.5.0
    CodeBase: file:///C:/Program%20Files/GammaLauncher/VL.AppServices.dll
----------------------------------------
System.Reactive
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.0.1
    CodeBase: file:///C:/Program%20Files/GammaLauncher/System.Reactive.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Threading.Thread.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.1423.7402
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.14/System.Windows.Forms.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.1423.7402
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.14/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Diagnostics.TraceSource.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.ComponentModel.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Collections.Specialized.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.14/System.Drawing.Common.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/Microsoft.Win32.Primitives.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.1423.7402
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.14/Accessibility.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.ComponentModel.dll
----------------------------------------
Microsoft.VisualStudio.Threading
    Assembly Version: 17.2.0.0
    Win32 Version: 17.2.32.20631
    CodeBase: file:///C:/Program%20Files/GammaLauncher/Microsoft.VisualStudio.Threading.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Collections.Concurrent.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Collections.Immutable.dll
----------------------------------------
Irony
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0
    CodeBase: file:///C:/Program%20Files/GammaLauncher/Irony.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Runtime.Loader.dll
----------------------------------------
VL.CoreLib
    Assembly Version: 2022.5.0.0
    Win32 Version: 2022.5.0
    CodeBase: file:///C:/Program%20Files/GammaLauncher/VL.CoreLib.dll
----------------------------------------
VL.Core.Skia
    Assembly Version: 2022.5.0.0
    Win32 Version: 2022.5.0
    CodeBase: file:///C:/Program%20Files/GammaLauncher/VL.Core.Skia.dll
----------------------------------------
ImGui.NET
    Assembly Version: 1.89.2.0
    Win32 Version: 1.89.2
    CodeBase: file:///C:/Program%20Files/GammaLauncher/ImGui.NET.dll
----------------------------------------
SkiaSharp
    Assembly Version: 2.88.0.0
    Win32 Version: 2.88.1.0
    CodeBase: file:///C:/Program%20Files/GammaLauncher/SkiaSharp.dll
----------------------------------------
FsPickler
    Assembly Version: 5.3.2.0
    Win32 Version: 5.3.2.0
    CodeBase: file:///C:/Program%20Files/GammaLauncher/FsPickler.dll
----------------------------------------
FSharp.Core
    Assembly Version: 4.4.3.0
    Win32 Version: 2018.1.25.1
    CodeBase: file:///C:/Program%20Files/GammaLauncher/FSharp.Core.dll
----------------------------------------
System.Xml.XDocument
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Xml.XDocument.dll
----------------------------------------
System.Private.Xml.Linq
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Private.Xml.Linq.dll
----------------------------------------
System.Memory
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Memory.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Private.Xml.dll
----------------------------------------
System.Console
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Console.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.ObjectModel.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Text.RegularExpressions.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Reflection.Primitives.dll
----------------------------------------
VL.CoreLib.vl
    Assembly Version: 0.0.0.0
    Win32 Version: 
    CodeBase: file:///C:/Program%20Files/GammaLauncher/VL.CoreLib.vl.dll
----------------------------------------
CommunityToolkit.HighPerformance
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.0.1
    CodeBase: file:///C:/Program%20Files/GammaLauncher/CommunityToolkit.HighPerformance.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
System.Interactive
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1.35981
    CodeBase: file:///C:/Program%20Files/GammaLauncher/System.Interactive.dll
----------------------------------------
System.Net.Sockets
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Net.Sockets.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Net.Primitives.dll
----------------------------------------
System.Net.Requests
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Net.Requests.dll
----------------------------------------
System.IO.Ports
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.21.52210
    CodeBase: file:///C:/Program%20Files/GammaLauncher/System.IO.Ports.dll
----------------------------------------
System.Net.NetworkInformation
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Net.NetworkInformation.dll
----------------------------------------
System.Net.Ping
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Net.Ping.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.21.52210
    CodeBase: file:///C:/Program%20Files/GammaLauncher/System.Management.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.ComponentModel.TypeConverter.dll
----------------------------------------
VL.Skia.vl
    Assembly Version: 0.0.0.0
    Win32 Version: 
    CodeBase: file:///C:/Program%20Files/GammaLauncher/VL.Skia.vl.dll
----------------------------------------
VL.Skia
    Assembly Version: 2022.5.0.0
    Win32 Version: 2022.5.0
    CodeBase: file:///C:/Program%20Files/GammaLauncher/VL.Skia.dll
----------------------------------------
VL.CoreLib.Windows.vl
    Assembly Version: 0.0.0.0
    Win32 Version: 
    CodeBase: file:///C:/Program%20Files/GammaLauncher/VL.CoreLib.Windows.vl.dll
----------------------------------------
VL.CoreLib.Windows
    Assembly Version: 2022.5.0.0
    Win32 Version: 2022.5.0
    CodeBase: file:///C:/Program%20Files/GammaLauncher/VL.CoreLib.Windows.dll
----------------------------------------
VL.ImGui.vl
    Assembly Version: 0.0.0.0
    Win32 Version: 
    CodeBase: file:///C:/Program%20Files/GammaLauncher/VL.ImGui.vl.dll
----------------------------------------
VL.ImGui
    Assembly Version: 2022.5.0.0
    Win32 Version: 2022.5.0
    CodeBase: file:///C:/Program%20Files/GammaLauncher/VL.ImGui.dll
----------------------------------------
SixLabors.Fonts
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/GammaLauncher/SixLabors.Fonts.dll
----------------------------------------
System.Resources.ResourceManager
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Resources.ResourceManager.dll
----------------------------------------
VL.ImGui.Skia.vl
    Assembly Version: 0.0.0.0
    Win32 Version: 
    CodeBase: file:///C:/Program%20Files/GammaLauncher/VL.ImGui.Skia.vl.dll
----------------------------------------
VL.WinFormsUtils.vl
    Assembly Version: 0.0.0.0
    Win32 Version: 
    CodeBase: file:///C:/Program%20Files/GammaLauncher/VL.WinFormsUtils.vl.dll
----------------------------------------
RestSharp
    Assembly Version: 106.15.0.0
    Win32 Version: 106.15.0
    CodeBase: file:///C:/Program%20Files/GammaLauncher/RestSharp.dll
----------------------------------------
Downloader
    Assembly Version: 3.0.3.0
    Win32 Version: 3.0.3.0
    CodeBase: file:///C:/Program%20Files/GammaLauncher/Downloader.dll
----------------------------------------
Semver
    Assembly Version: 2.0.6.0
    Win32 Version: 2.0.6.0
    CodeBase: file:///C:/Program%20Files/GammaLauncher/Semver.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Diagnostics.Process.dll
----------------------------------------
SkiaSharp.Extended.Svg
    Assembly Version: 1.60.0.0
    Win32 Version: 1.60.0.0
    CodeBase: file:///C:/Program%20Files/GammaLauncher/SkiaSharp.Extended.Svg.dll
----------------------------------------
VL.ImGui.Skia
    Assembly Version: 2022.5.0.0
    Win32 Version: 2022.5.0
    CodeBase: file:///C:/Program%20Files/GammaLauncher/VL.ImGui.Skia.dll
----------------------------------------
SharpDX.MediaFoundation
    Assembly Version: 4.2.0.0
    Win32 Version: 4.2.0
    CodeBase: file:///C:/Program%20Files/GammaLauncher/SharpDX.MediaFoundation.dll
----------------------------------------
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/mscorlib.dll
----------------------------------------
System.IO.FileSystem.Watcher
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.IO.FileSystem.Watcher.dll
----------------------------------------
System.Xml.XmlSerializer
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Xml.XmlSerializer.dll
----------------------------------------
System.Text.Json
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Text.Json.dll
----------------------------------------
System.Net.Http
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Net.Http.dll
----------------------------------------
System.Net.WebHeaderCollection
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Net.WebHeaderCollection.dll
----------------------------------------
System.Web.HttpUtility
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Web.HttpUtility.dll
----------------------------------------
System.Xml.XPath.XDocument
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Xml.XPath.XDocument.dll
----------------------------------------
System.Net.WebClient
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Net.WebClient.dll
----------------------------------------
SkiaSharp.Skottie
    Assembly Version: 2.88.0.0
    Win32 Version: 2.88.1.0
    CodeBase: file:///C:/Program%20Files/GammaLauncher/SkiaSharp.Skottie.dll
----------------------------------------
SkiaSharp.SceneGraph
    Assembly Version: 2.88.0.0
    Win32 Version: 2.88.1.0
    CodeBase: file:///C:/Program%20Files/GammaLauncher/SkiaSharp.SceneGraph.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Numerics.Vectors.dll
----------------------------------------
Humanizer
    Assembly Version: 2.14.0.0
    Win32 Version: 2.14.1.48190
    CodeBase: file:///C:/Program%20Files/GammaLauncher/Humanizer.dll
----------------------------------------
System.Reflection.Emit
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Reflection.Emit.dll
----------------------------------------
__AdaptiveImplementations.1__
    Assembly Version: 0.0.0.0
    Win32 Version: 2022.5.0
    CodeBase: file:///C:/Program%20Files/GammaLauncher/VL.AppServices.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Collections.NonGeneric.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Threading.ThreadPool.dll
----------------------------------------
System.Linq.Expressions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Linq.Expressions.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Private.CoreLib.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Text.Encoding.Extensions.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.14/System.Reflection.Metadata.dll
----------------------------------------

************** JIT Debugging **************
```

**Comment by sunep** [comment]
yep, that fixed it

**Comment by sebescudie** [comment]
Yo @sunep, closing this one but please feel free to re-open if you see that again.
