### ISSUE TITLE
"Root Element Is Missing" Exception

### ISSUE THREAD

**Issue by berkut0** [sebescudie/GammaLauncher#84]
Disc C ran out of space and overwriting the configuration file corrupted the file (main hypothesis). Now the error occurs even after reinstalling. I will look for the problem, not sure if I can fix it myself. But most importantly, I think it's worth fixing in the future.

![Screenshot_56](https://github.com/user-attachments/assets/8e6a512b-4aa0-4752-8629-5c0f754dbdb8)

<details>
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(Stream stream, LoadOptions options)
   at VL.Lib.IO.XDocumentReader.Read(IResourceProvider`1 provider)
   at VL.Lib.IO.XDocumentReader.Update(IResourceProvider`1 input, Boolean read)
   at _VL_Xml_.System.XML.XMLReader_XDocument_OPrbd3hV1yTQAohaXbZTAZ.Update(Path File_Path_In, Boolean Read_In, XDocument& Output_Out)
   at _VL_Xml_.System.XML.XMLReader_OcM6yTDIunKLXht5WzCyyW.Update(Path File_Path_In, Boolean Read_In, XElement& Output_Out)
   at _GammaLauncher_.Main.Editor.File.UserSettingsInitializer_LzkfZhpne9PPdBDTgZZnhU.__Create__(NodeContext Node_Context, IChannel`1 Input_In, IChannel`1& Output_Out, Rectangle& Initial_Window_Bounds_Out)
   at _GammaLauncher_.Main.Editor.File.UserSettingsInitializer_LzkfZhpne9PPdBDTgZZnhU.Create(NodeContext Node_Context, IChannel`1 Input_In, IChannel`1& Output_Out, Rectangle& Initial_Window_Bounds_Out)
   at _GammaLauncher_.Main.App.App_C.__Create__(NodeContext Node_Context, Rectangle& Initial_Window_Bounds_Out)
   at _GammaLauncher_.Main.App.App_C.Create(NodeContext Node_Context, Rectangle& Initial_Window_Bounds_Out)
   at _GammaLauncher_.__auto.GammaLauncherApplication_OvsYGMYpBALLYRzDG73d7z.__Create__(NodeContext Node_Context)
   at _GammaLauncher_.__auto.GammaLauncherApplication_OvsYGMYpBALLYRzDG73d7z.Create(NodeContext Node_Context)
   at Program.<>c.<Main>b__0_0(NodeContext c)
   at VL.AppServices.ExportedAppHost.<>c__DisplayClass30_1.<RunCoreAsync>b__1(Object _)
```
</detals>

**Comment by berkut0** [comment]
I deleted files from a folder and now it runs.

![Screenshot_58](https://github.com/user-attachments/assets/323b9efe-4053-4c72-8558-8686548680d9)

**Comment by sebescudie** [comment]
Yep, it looks like those settings file sometimes get corrupted, no idea why. The Launcher should catch that more gracefully than throwing an Exception at your face.
